#!/bin/sh
set -x
sysctl -w kernel.shmmax=17179869184 # for postgres
/opt/opscode/embedded/bin/runsvdir-start &

if [ x"$(hostname)" != x"$(grep server_name /etc/opscode/chef-server-running.json | sed 's/.*\"\(.*\)\".*\"\(.*\)\".*/\2/')" ]; then
	echo "Hostname changed, chef-server must be reconfigured"
	chef-server-ctl reconfigure
	# Wait for error
	chef-server-ctl stop
	chef-server-ctl reconfigure
fi

 /usr/bin/chef-server-ctl start
tail -F /opt/opscode/embedded/service/*/log/current
